spring:
  profiles: development
  mail:
    username: ${emailId}
    password: ${emailPass}
  rabbitmq:
    username: ${rabbitUser}
    password: ${rabbitPass}
url: jdbc:mysql://localhost:3306/${dbName}?useSSL=false
dbUserName: ${dbUser}
dbPassword: ${dbPass}
driverClassName: com.mysql.cj.jdbc.Driver
  