spring:
  profiles: development
  mail:
    username: ${emailId}
    password: ${emailPass}

  url: jdbc:mysql://localhost:3306/${dbName}?useSSL=false
  dbUserName: ${dbUser}
  dbPassword: ${dbPass}
  driverClassName: com.mysql.cj.jdbc.Driver
  rabbitmq:
    username: ${rabbitUser}
    password: ${rabbitPass}